### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by shishirkh** [flaccid/docker-redis-sentinel-proxy#1]
Thanks for this tool.

I want to use it on a ipv6 env. However I get the following errors in logs.

2021/04/28 16:13:54 address 240b:c0e0:202:5e2b:b424:2:0:961d:6379: too many colons in address
2021/04/28 16:13:55 address 240b:c0e0:202:5e2b:b424:2:0:961d:6379: too many colons in address
2021/04/28 16:13:56 address 240b:c0e0:202:5e2b:b424:2:0:961d:6379: too many colons in address
2021/04/28 16:13:57 address 240b:c0e0:202:5e2b:b424:2:0:961d:6379: too many colons in address
2021/04/28 16:13:58 address 240b:c0e0:202:5e2b:b424:2:0:961d:6379: too many colons in address
2021/04/28 16:13:59 address 240b:c0e0:202:5e2b:b424:2:0:961d:6379: too many colons in address
2021/04/28 16:14:00 address 240b:c0e0:202:5e2b:b424:2:0:961d:6379: too many colons in addr

- I think a small parsing fix such as enclosing the addr in square brackets i.e. [ ] can fix it. 
- a new parameter to switch between ipv4 and ipv6 will be needed too.

I can help in testing this out if someone can make the above code changes.

**Comment by flaccid** [comment]
@shishirkh happy to take a pull request!

**Comment by shishirkh** [comment]
You can watch out for this PR -> https://github.com/enriclluelles/redis-sentinel-proxy/pull/7

**Comment by flaccid** [comment]
Totally upstream source; fyi @enriclluelles.
